---

- name: install operator
  command: >-
    kubectl create
    --kubeconfig /etc/kubernetes/admin.conf
    -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/tigera-operator.yaml

- name: create custom-resource
  command: >-
    kubectl create
    --kubeconfig /etc/kubernetes/admin.conf
    -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/custom-resources.yaml
