---

- name: apt upgrade
  apt:
    name: '*'
    update_cache: yes

- name: install requirements
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ k8s_containerd_requirement_packages }}"

- name: mkdir /etc/apt/keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: 0755

- name: add docker.gpg
  shell: >-
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: add docker repo
  shell: >-
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable"
  register: docker_repo_result
  changed_when: false

- name: add docker repo
  set_fact:
    docker_repo: "{{ docker_repo_result.stdout }}"

- name: add docker repo
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: 0644

- name: install containerd.io
  apt:
    name: containerd.io
    update_cache: yes

- name: config containerd
  copy:
    src: config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: 0644

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
